version: "3"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - flask
    ports:
      - "443:443"
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3306"
