version: '2'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - sql
  sql:
    build: .
    environment:
      - DB=mariadb
      - PREFIX=/sql
    depends_on:
      - mariadb
    volumes:
      - ./app:/var/www/app
  mariadb:
    image: mariadb
    logging:
      driver: none
    environment:
      - MYSQL_ROOT_PASSWORD=root
